dokter/urls.py
from django.urls import path

from . import views

app_name = 'dokter'

urlpatterns = [
    path('createSchedule/', views.createSchedule, name='createSchedule'),
    path('readDoctorSchedule/', views.readDoctorSchedule, name='readDoctorSchedule'),
]

pasien/urls.py
from django.urls import path

from . import views

app_name = 'pasien'

urlpatterns = [
    path('create/', views.createPasien, name='createPasien'),
    path('read/', views.readPasien, name='readPasien'),
    path('detail/<pk>/', views.detailPasien, name='detailPasien'),
    path('update/<pk>/', views.updatePasien, name='updatePasien'),
    path('delete/<pk>/', views.deletePasien, name='deletePasien')
]

pengguna/urls.py
from django.urls import path

from . import views

app_name = 'pengguna'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.loginview, name='login'),
    path('register/', views.registerview, name='register'),
    path("logout/", views.logoutview, name="logout"),
]

roomnbed/urls.py
from django.urls import path

from . import views

app_name = 'roomnbed'

urlpatterns = [
    path('createRuangan/', views.createRuangan, name='createRuangan'),
    path('kodeRuangan/', views.kodeRuangan, name='koderuangan'),
    path('createBed/', views.createBed, name='createBed'),
    path('kodeRuanganBed/', views.kodeRuanganBed, name='kodeRuanganBed'),
    path('kodeBed/', views.kodeBed, name='kodeBed'),
    path('readRuangan/', views.readRuangan, name='readRuangan'),
    path('readBed/', views.readBed, name='readBed'),
    path('updateRuangan/<param1>/<param2>', views.updateRuangan, name='updateRuangan'),
    path('deleteBed/<param1>/<param2>/<param3>/', views.deleteBed, name='deleteBed')
]

rs/urls.py
from django.urls import path

from . import views

app_name = 'rs'

urlpatterns = [
    path('', views.read, name='read'),
    path('create/', views.create, name='create'),
    path('update/<str:kode_faskes>', views.update, name='update'),
    path('updatePost/', views.updatePost, name='updatePost'),
]

siruco_e16/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("transaksi-makan/", include("transaksi_makan.urls")),
    path("paket-makan/", include("paket_makan.urls")),
    path("hotel/", include("hotel.urls")),
    path('', include('pengguna.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('reservasirs/', include('reservasirs.urls')),
    path('jadwalfaskes/', include('jadwalfaskes.urls')),
    path('rs/', include('rs.urls')),
    path('transaksirs/', include('transaksirs.urls')),
    path('dokter/', include('dokter.urls')),
    path('appointment/', include('appointment.urls')),
    path('roomnbed/', include('roomnbed.urls')),

]

siruco_e16/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Siruco</title>
    {% block meta %}{% endblock meta %}
  </head>
<body>
  <div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'pengguna:index' %}">Tolong</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'pengguna:index' %}">Home</a>
              </li>
              {% if request.session.username %}
                  {% if request.session.peran == "admin sistem" %}
                  <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Hotel
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="#">Buat Hotel</a></li>
                      <li><a class="dropdown-item" href="#">List Hotel</a></li>
                      <li><a class="dropdown-item" href="#">Buat Ruangan Hotel</a></li>
                      <li><a class="dropdown-item" href="#">List Ruangan Hotel</a></li>
                      <li><a class="dropdown-item" href="#">Buat Paket Makan</a></li>
                      <li><a class="dropdown-item" href="#">List Paket Makan</a></li>
                    </ul>
                  </li>
                  {% elif request.session.peran == "pengguna publik" %}

                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Pasien
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'pasien:createPasien' %}">Pendaftaran Pasien</a></li>
                          <li><a class="dropdown-item" href="#">List Pasien</a></li>
                          <li><a class="dropdown-item" href="{% url 'appointment:createAppointment' %}">Buat Appointment</a></li>
                          <li><a class="dropdown-item" href="#">List Appointment</a></li>
                          <li><a class="dropdown-item" href="#">List Hasil Test Pasien</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Rumah Sakit
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">List Jadwal Dokter</a></li>
                          <li><a class="dropdown-item" href="#">List Reservasi RS</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Hotel
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">List Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Ruangan Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Paket Makan</a></li>
                          <li><a class="dropdown-item" href="#">Buat Reservasi Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Reservasi Hotel</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Transaksi
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">Bayar Transaksi RS</a></li>
                          <li><a class="dropdown-item" href="#">Bayar Transaksi Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Transaksi Booking Hotel</a></li>
                          <li><a class="dropdown-item" href="#">Buat Transaksi Makan dan Daftar Pesan</a></li>
                          <li><a class="dropdown-item" href="#">List Transaksi Makan dan Daftar Pesan</a></li>
                        </ul>
                  </li>

                  {% elif request.session.peran == "dokter" %}

                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Pasien
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">List Appointment</a></li>
                          <li><a class="dropdown-item" href="#">Buat Hasil Test Pasien</a></li>
                          <li><a class="dropdown-item" href="#">List Hasil Test Pasien</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Rumah Sakit
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'dokter:createSchedule' %}">Buat Jadwal Dokter</a></li>
                          <li><a class="dropdown-item" href="#">List Jadwal Dokter</a></li>
                        </ul>
                  </li>

                  {% elif request.session.peran == "admin satgas" %}

                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Pasien
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'appointment:createAppointment' %}">Buat Appointment</a></li>
                          <li><a class="dropdown-item" href="#">List Appointment</a></li>
                          <li><a class="dropdown-item" href="#">List Hasil Test Pasien</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Faskes
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">Buat Faskes</a></li>
                          <li><a class="dropdown-item" href="#">List Faskes</a></li>
                          <li><a class="dropdown-item" href="#">Buat Jadwal Faskes</a></li>
                          <li><a class="dropdown-item" href="#">List Jadwal Faskes</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Rumah Sakit
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">Buat RS</a></li>
                          <li><a class="dropdown-item" href="#">List RS</a></li>
                          <li><a class="dropdown-item" href="#">List Jadwal Dokter</a></li>
                          <li><a class="dropdown-item" href="{% url 'roomnbed:createRuangan' %}">Buat Ruangan RS</a></li>
                          <li><a class="dropdown-item" href="{% url 'roomnbed:readRuangan' %}">List Ruangan RS</a></li>
                          <li><a class="dropdown-item" href="{% url 'roomnbed:createBed' %}">Buat Bed RS</a></li>
                          <li><a class="dropdown-item" href="{% url 'roomnbed:readBed' %}">List Bed RS</a></li>
                          <li><a class="dropdown-item" href="#">Buat Reservasi RS</a></li>
                          <li><a class="dropdown-item" href="#">Liat Reservasi RS</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Hotel
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">List Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Ruangan Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Paket Makan</a></li>
                          <li><a class="dropdown-item" href="#">Buat Reservasi Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Reservasi Hotel</a></li>
                        </ul>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Transaksi
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="#">List Transaksi RS</a></li>
                          <li><a class="dropdown-item" href="#">List Transaksi Hotel</a></li>
                          <li><a class="dropdown-item" href="#">List Transaksi Booking Hotel</a></li>
                          <li><a class="dropdown-item" href="#">Buat Transaksi Makan dan Daftar Pesan</a></li>
                          <li><a class="dropdown-item" href="#">List Transaksi Makan dan Daftar Pesan</a></li>
                        </ul>
                  </li>


                  {% endif %}
              {% else %}
              engga amsuk
              {% endif %}
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="content">
      {% block content %}
      {% endblock content %}
    </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

</body>
</html>