hotel/urls.py
from django.urls import path

from . import views

app_name = 'hotel'

urlpatterns = [
    path('', views.index, name='index'),
    path("create/", views.create_hotel,name="create_hotel"),
    path("create/submit/", views.submit_create_hotel, name="submit_create_hotel"),
    path("update/<str:kode_hotel>/", views.update_hotel,name="update_hotel"),
    path("update/post/submit/", views.submit_update_hotel,name="submit_update_hotel"),
    path('kodeRuangan/', views.kodeRuangan, name='kodeRuanganAsync'),
    path('createHotelRoom/', views.createHotelRoom, name='createHotelRoom'),
    path('readHotelRoom/', views.readHotelRoom, name='readHotelRoom'),
    path('updateHotelRoom/<param1>/<param2>', views.updateHotelRoom, name='updateHotelRoom'),
    path('deleteHotelRoom/<str:param1>/<str:param2>', views.deleteHotelRoom, name='deleteHotelRoom'),
    path('createHotelReservation/', views.createHotelReservation, name='createHotelReservation'),
    path('kodeRuanganAll/', views.getAllKodeRuangan, name='kodeRuanganAll'),
    path('readHotelReservation/', views.readHotelReservation, name='readHotelReservation'),
    path('updateHotelReservation/<param1>/<param2>', views.updateHotelReservation, name='updateHotelReservation'),
    path('deleteHotelReservation/<param1>/<param2>', views.deleteHotelReservation, name='deleteHotelReservation'),
    path('readTransaksiHotel/', views.readTransaksiHotel, name='readTransaksiHotel'),
    path('updateTransaksiHotel/<pk>', views.updateTransaksiHotel, name='updateTransaksiHotel'),
    path('readTransaksiBooking', views.readTransaksiBooking, name='readTransaksiBooking')
]

rs/urls.py
from django.urls import path

from . import views

app_name = 'rs'

urlpatterns = [
    path('', views.read, name='read'),
    path('create/', views.create, name='create'),
    path('update/<str:kode_faskes>', views.update, name='update'),
    path('updatePost/', views.updatePost, name='updatePost'),
]

siruco_e16/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("transaksi-makan/", include("transaksi_makan.urls")),
    path("paket-makan/", include("paket_makan.urls")),
    path("hotel/", include("hotel.urls")),
    path('', include('pengguna.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('reservasirs/', include('reservasirs.urls')),
    path('jadwalfaskes/', include('jadwalfaskes.urls')),
    path('rs/', include('rs.urls')),
    path('transaksirs/', include('transaksirs.urls')),
    path('dokter/', include('dokter.urls')),
    path('appointment/', include('appointment.urls')),
    path('roomnbed/', include('roomnbed.urls')),

]

hotel/models.py
from django.db import models

# Create your models here.

hotel/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.contrib import messages
from django.http import JsonResponse
import json
import traceback
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def index(request):
    admin_sistem = False
    public_dan_satgas = False


    nama = request.session.get("username")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from akun_pengguna
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("pengguna:index")
    
    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from pengguna_publik
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) != 0):
            public_dan_satgas = True

        
    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from admin_satgas
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) != 0):
            public_dan_satgas = True

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select *
            from admin a
            where a.username not in 
            (
                select ads.username
                from admin_satgas ads
            ) and a.username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) != 0):
            admin_sistem = True

    if (not (admin_sistem or public_dan_satgas)):
        return redirect("pengguna:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select kode, nama, isrujukan, 
            concat(jalan, ', ', kelurahan, ', ', kecamatan, ', ', kabkot, ', ', prov)
            from hotel
            order by kode asc;
        """)

        row = cursor.fetchall()
        
        hotel_query = [
            (no, item[0], item[1], item[2], item[3]) for (no, item)
            in enumerate(row, start=1)
        ]
    
            
        print(hotel_query)
        context = {
            "hotel_query" : hotel_query,  
            "admin_sistem" : admin_sistem,
            "public_dan_satgas" : public_dan_satgas
        }

    return render(request, "hotel/index.html", context=context)   

def create_hotel(request):
    admin_sistem = False

    nama = request.session.get("username")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from akun_pengguna
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("pengguna:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select *
            from admin a
            where a.username not in 
            (
                select ads.username
                from admin_satgas ads
            ) and a.username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("hotel:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select kode
            from hotel
            order by kode desc
            limit 1;
        """)
        row = cursor.fetchall()
        max_id = row[0][0]
        max_id = "HTL-6"
        max_id = max_id.split("-")[1]
        max_id = 1 + int(max_id)
        if max_id < 10:
            max_id = str('HTL-' + str(max_id))
        else:
            max_id = str('HT-' + str(max_id))
    context = {
        "max_id" : max_id,
    }
    return render(request, "hotel/create.html", context=context)


@csrf_exempt
def submit_create_hotel(request):
    admin_sistem = False

    nama = request.session.get("username")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from akun_pengguna
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("pengguna:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select *
            from admin a
            where a.username not in 
            (
                select ads.username
                from admin_satgas ads
            ) and a.username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("hotel:index")

    if request.is_ajax and request.method == "POST":
        data = json.loads(request.body.decode('utf-8'))
        print(data)
        kode_hotel = data.get("kodeHotel")
        nama_hotel = data.get("namaHotel")
        is_rujukan = data.get("isRujukan")
        jalan = data.get("jalan")
        kelurahan = data.get("kelurahan")
        kecamatan = data.get("kecamatan")
        kabkot = data.get("kabkot")
        provinsi = data.get("provinsi")
        
        with connection.cursor() as cursor:
            cursor.execute(f"""
                INSERT INTO HOTEL(Kode, Nama, isRujukan, Jalan, Kelurahan, Kecamatan, KabKot, Prov) VALUES
                ('{kode_hotel}', '{nama_hotel}', '{is_rujukan}', '{jalan}', '{kelurahan}', '{kecamatan}', '{kabkot}', '{provinsi}');
            """)
        return JsonResponse({}, status = 200)

@csrf_exempt
def update_hotel(request, kode_hotel):
    admin_sistem = False

    nama = request.session.get("username")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from akun_pengguna
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("pengguna:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select *
            from admin a
            where a.username not in 
            (
                select ads.username
                from admin_satgas ads
            ) and a.username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("hotel:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from hotel
            where kode = '{kode_hotel}';
        """)
        row = cursor.fetchall()
        print(row)
        hotel = row[0]
    context = {
        "hotel" : hotel,
    }
    return render(request, "hotel/update.html", context=context)

@csrf_exempt
def submit_update_hotel(request):
    admin_sistem = False

    nama = request.session.get("username")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select * 
            from akun_pengguna
            where username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("pengguna:index")

    with connection.cursor() as cursor:
        cursor.execute(f"""
            select *
            from admin a
            where a.username not in 
            (
                select ads.username
                from admin_satgas ads
            ) and a.username = '{nama}';
        """)
        row = cursor.fetchall()
        if (len(row) == 0):
            return redirect("hotel:index")

    if request.is_ajax and request.method == "POST":
        data = json.loads(request.body.decode('utf-8'))
        print(data)
        kode_hotel = data.get("kodeHotel")
        nama_hotel = data.get("namaHotel")
        is_rujukan = data.get("isRujukan")
        jalan = data.get("jalan")
        kelurahan = data.get("kelurahan")
        kecamatan = data.get("kecamatan")
        kabkot = data.get("kabkot")
        provinsi = data.get("provinsi")

        
        with connection.cursor() as cursor:
            cursor.execute(f"""
                UPDATE hotel
                SET nama = '{nama_hotel}',
                isrujukan = '{is_rujukan}',
                jalan = '{jalan}',
                kelurahan = '{kelurahan}',
                kecamatan = '{kecamatan}',
                kabkot = '{kabkot}',
                prov = '{provinsi}'
                WHERE kode = '{kode_hotel}';
            """)
        return JsonResponse({}, status = 200)


def createHotelRoom(request):

    if request.method == "POST":
        with connection.cursor() as cursor:
            try:
                print(f"{request.POST['kodeHotel']}, {request.POST['jenisBed']}, {request.POST['tipe']}, {request.POST['harga']}")
                cursor.execute(f"""
                    INSERT INTO HOTEL_ROOM (kodehotel, koderoom, jenisbed, tipe, harga) VALUES(
                        '{request.POST['kodeHotel']}', '{request.POST['kodeRuangan']}', '{request.POST['jenisBed']}', '{request.POST['tipe']}', '{request.POST['harga']}'
                    )
                """)
            except:
                traceback.print_exc()
                messages.add_message(request, messages.WARNING, "Terdapat internal error")
        
        # return redirect('hotel:readHotelRoom')

    kodeList = []

    with connection.cursor() as cursor:
        try:
            cursor.execute(f"""
                SELECT kode FROM HOTEL
            """)

            for kode in cursor.fetchall():
                kodeList.append(kode[0])
            
        except:
            pass
    
    return render(request, "hotel/createHotelRoom.html", {'kodeList' : kodeList})

def kodeRuangan(request):
    kodeHotel = request.GET['q']
    kodeRoom = ""

    with connection.cursor() as cursor:
        try:
            cursor.execute(f"""
                SELECT DISTINCT koderoom FROM HOTEL_ROOM
                WHERE kodehotel = '{kodeHotel}'
                ORDER BY koderoom DESC LIMIT 1;
            """)

            row = cursor.fetchone()

            print(row)

            if row != None:

hotel/templates/hotel/create.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<script src="{% static 'hotel/js/hotel_create.js' %}"></script>

<h1>FORM BUAT HOTEL</h1>

<div>Kode Hotel : 
    <label id="kode-hotel">{{max_id}}</label>
</div>
<label for="fname">Nama Hotel : </label>
<input type="text" id="nama-hotel" maxlength="30"></input> <br>
<label for="fname">Rujukan : </label>
<input type="checkbox" id="isrujukan"></input> <br>
<div>
    Alamat : 
    
</div>
<label for="fname">Jalan : </label>
<input type="text" id="jalan" maxlength="30"></input> <br>
<label for="fname">Kelurahan : </label>
<input type="text" id="kelurahan" maxlength="30"></input> <br>
<label for="fname">Kecamatan : </label>
<input type="text" id="kecamatan" maxlength="30"></input> <br>
<label for="fname">Kabupaten/Kota : </label>
<input type="text" id="kabkot" maxlength="30"></input> <br>
<label for="fname">Provinsi : </label>
<input type="text" id="provinsi" maxlength="30"></input> <br>

<div id="submit">SIMPAN</div>
<a href="{% url 'hotel:index' %}">KEMBALI</a>
{% endblock %}

hotel/templates/hotel/createHotelReservation.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<script src="{% static 'hotel/createHotelReservation.js' %}"></script>
{% endblock meta %}
{% block content %}

{% if messages %}
    <br>
    <h4>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    </h4>
{% endif %}
<h4>Form Reservasi Hotel</h4>
<br>
<form method="POST" action="{% url 'hotel:createHotelReservation' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="nikPasien" class="form-label">Nik Pasien</label>
        <select type="text" name="nikPasien" class="form-control" id="nikPasien" required>
            <option disabled selected value> -- select an option -- </option>
            {% for pasien in pasienList %}
            <option value="{{ pasien.0 }}">{{ pasien.0 }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="tglmasuk" class="form-label">Tanggal Masuk</label>
        <input type="date" name="tglmasuk" class="form-control" id="tglmasuk" required>
    </div>
    <div class="mb-3">
        <label for="tglkeluar" class="form-label">Tanggal Keluar</label>
        <input type="date" name="tglkeluar" class="form-control" id="tglkeluar" required>
    </div>
    <div class="mb-3">
        <label for="kodehotel" class="form-label">Kode Hotel</label>
        <select type="text" name="kodehotel" class="form-control" id="kodehotel" required>
            <option disabled selected value> -- select an option -- </option>
            {% for hotel in hotelList %}
            <option value="{{ hotel.0 }}">{{ hotel.0 }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="koderuangan" class="form-label">Kode Ruangan</label>
        <select type="text" name="koderuangan" class="form-control" id="koderuangan" required>
            <option disabled selected value> -- select an option -- </option>
            <!--Ajax value goes here-->
        </select>
    </div>
    <button type="submit" id="hotelRoomSubmit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

hotel/templates/hotel/createHotelRoom.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<script src="{% static 'hotel/kodeRoom.js' %}"></script>
{% endblock meta %}
{% block content %}

{% if messages %}
    <br>
    <h4>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    </h4>
{% endif %}

<form method="POST" action="{% url 'hotel:createHotelRoom' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="kodeHotel" class="form-label">Kode Hotel</label>
        <select type="text" name="kodeHotel" class="form-control" id="kodeHotel" required>
            <option disabled selected value> -- select an option -- </option>
            {% for kode in kodeList %}
            <option value="{{ kode }}">{{ kode }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="kodeRuangan" class="form-label">Kode Ruangan</label>
        <input type="text" name="kodeRuangan" class="form-control" id="kodeRuangan" readonly>
    </div>
    <div class="mb-3">
        <label for="jenisBed" class="form-label">Jenis Bed</label>
        <input type="text" name="jenisBed" class="form-control" id="jenisBed" required>
    </div>
    <div class="mb-3">
        <label for="tipe" class="form-label">Tipe</label>
        <input type="text" name="tipe" class="form-control" id="tipe" required>
    </div>
    <div class="mb-3">
        <label for="harga" class="form-label">Harga per hari (dalam ribu Rupiah)</label>
        <input type="text" name="harga" class="form-control" id="harga" required>
    </div>
    <button type="submit" id="hotelRoomSubmit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

hotel/templates/hotel/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- JS External -->
<script src="{% static 'hotel/js/hotel_index.js' %}"></script>
<style>
    table, th, td {
      border: 1px solid black;
    }

    table {
  width: 100%;
  border-collapse: collapse;
    }
</style>

<h1>Hotel</h1>
{% if admin_sistem %}
<a href="{% url 'hotel:create_hotel' %}">TAMBAH</a>
{% endif %} 
<table class="table mt-3">
    <thead class="bg-1">
      <tr>
        <th scope="col">No</th>
        <th scope="col">Kode</th>
        <th scope="col">Hotel</th>
        <th scope="col">Rujukan</th>
        <th scope="col">Alamat</th>
        {% if admin_sistem %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
        {% for hotel in hotel_query %}
            <tr class="bg-4">
                <th class="idNo" scope="row">{{hotel.0}}</th>
                <td class="kode-hotel">{{hotel.1}}</td>
                <td class="nama-hotel">{{hotel.2}}</td>
                <td>
                  {% if hotel.3 == "1" %}
                  <input type="checkbox" checked disabled></input>
                  {% else %}
                  <input type="checkbox" disabled></input>
                  {% endif %}
                </td>
                <td>
                  <div id="alamat">{{hotel.4}}</div>
                </td>
                {% if admin_sistem %}
                <td>    
                    <div class="update-url">
                    update
                    </div>
                </td>
                {% endif %}
            </tr>     
        {% endfor %}
    </tbody>
</table>

{% endblock %}

hotel/templates/hotel/readHotelReservation.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
<br>
<h4>
{% for message in messages %}
    {{ message }}
{% endfor %}
</h4>
{% endif %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">NIK Pasien</th>
        <th scope="col">Tanggal Masuk</th>
        <th scope="col">Tanggal Keluar</th>
        <th scope="col">Kode Hotel</th>
        <th scope="col">Ruangan</th>
        {% if request.session.peran == "admin satgas" %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for hotelReservation in listHotelReservation %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ hotelReservation.0 }}</td>
        <td>{{ hotelReservation.1 }}</td>
        <td>{{ hotelReservation.2 }}</td>
        <td>{{ hotelReservation.3 }}</td>
        <td>{{ hotelReservation.4 }}</td>
        {% if request.session.peran == "admin satgas" %}
        <td> 
            <a href="{% url 'hotel:updateHotelReservation' hotelReservation.0 hotelReservation.1 %}">Update</a>
            {% if hotelReservation.5 %}
             | <a href="{% url 'hotel:deleteHotelReservation' hotelReservation.0 hotelReservation.1 %}">Delete</a>
            {% endif %}
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

hotel/templates/hotel/readHotelRoom.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
<br>
<h4>
{% for message in messages %}
    {{ message }}
{% endfor %}
</h4>
{% endif %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Kode Hotel</th>
        <th scope="col">Kode Ruangan</th>
        <th scope="col">Jenis Bed</th>
        <th scope="col">Tipe</th>
        <th scope="col">Harga</th>
        {% if request.session.peran == "admin sistem" %}
        <th scope="col">Action</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for hotelRoom in listHotelRoom %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ hotelRoom.0 }}</td>
        <td>{{ hotelRoom.1 }}</td>
        <td>{{ hotelRoom.2 }}</td>
        <td>{{ hotelRoom.3 }}</td>
        <td>Rp.{{ hotelRoom.4 }}</td>
        {% if request.session.peran == "admin sistem" %}
        <td> 
            <a href="{% url 'hotel:updateHotelRoom' hotelRoom.0 hotelRoom.1 %}">Update</a>
            {% if hotelRoom.5 %}
             | <a href="{% url 'hotel:deleteHotelRoom' hotelRoom.0 hotelRoom.1 %}">Delete</a>
            {% endif %}
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

hotel/templates/hotel/readTransaksiHotel.html
{% extends 'base.html' %}

{% block content %}

{% if messages %}
<br>
<h4>
{% for message in messages %}
    {{ message }}
{% endfor %}
</h4>
{% endif %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Id Transaksi</th>
        <th scope="col">NIK Pasien</th>
        <th scope="col">Tanggal Pembayaran</th>
        <th scope="col">Waktu Pembayaran</th>
        <th scope="col">Total Bayar</th>
        <th scope="col">Status</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for transaksiHotel in listTransaksiHotel %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ transaksiHotel.0 }}</td>
        <td>{{ transaksiHotel.1 }}</td>
        <td>{{ transaksiHotel.2 }}</td>
        <td>{{ transaksiHotel.3 }}</td>
        <td>{{ transaksiHotel.4 }}</td>
        <td>{{ transaksiHotel.5 }}</td>
        <td><a href="{% url 'hotel:updateTransaksiHotel' transaksiHotel.0 %}">Update</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

hotel/templates/hotel/updateHotelReservation.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
    <br>
    <h4>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    </h4>
    {% endif %}

<h4>Form Update Hotel Reservation</h4>
<form method="POST" action="{% url 'hotel:updateHotelReservation' hotelReservationDetail.0 hotelReservationDetail.1 %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="disabledInput" class="form-label">NIK Pasien</label>
        <input class="form-control" name="kodepasien" id="disabledInput" value="{{hotelReservationDetail.0}}" type="text" placeholder="{{hotelReservationDetail.0}}" readonly>
    </div>
    <div class="mb-3">
      <label for="tglmasuk" class="form-label">Tanggal Masuk {{hotelReservationDetail.1}}</label>
      <input type="date" name="tglmasuk" class="form-control" id="tglmasuk" value="{{hotelReservationDetail.1|date:'Y-m-d'}}" placeholder="{{hotelReservationDetail.1}}" readonly>
    </div>
    <div class="mb-3">
      <label for="tglkeluar" class="form-label">Tanggal Keluar</label>
      <input type="date" name="tglkeluar" class="form-control" id="tglkeluar" placeholder="{{ hotelReservationDetail.2 }}" required>
    </div>
    <div class="mb-3">
        <label for="kodehotel" class="form-label">Hotel</label>
        <input type="text" name="kodehotel" class="form-control" id="kodehotel" value="{{ hotelReservationDetail.3 }}" placeholder="{{ hotelReservationDetail.3 }}" readonly>
    </div>
    <div class="mb-3">
        <label for="koderoom" class="form-label">Ruangan</label>
        <input type="text" name="koderoom" class="form-control" id="koderoom" value="{{ hotelReservationDetail.4 }}" placeholder="{{ hotelReservationDetail.4 }}" readonly>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<script>
    console.log($('#tglmasuk').val())
    var tglmasuk = new Date($('#tglmasuk').val());
    var minimumTglMasuk = new Date(tglmasuk.valueOf() + 1000*3600*24).toISOString().split('T')[0]
    console.log(minimumTglMasuk);
    $('#tglkeluar').attr("min", minimumTglMasuk);
</script>

{% endblock content %}

hotel/templates/hotel/updateHotelRoom.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
    <br>
    <h4>
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    </h4>
    {% endif %}

<h4>Form Update Hotel Room</h4>
<form method="POST" action="{% url 'hotel:updateHotelRoom' hotelRoomDetail.0 hotelRoomDetail.1 %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="disabledInput" class="form-label">Kode Hotel</label>
        <input class="form-control" name="kodehotel" id="disabledInput" value="{{hotelRoomDetail.0}}" type="text" placeholder="{{hotelRoomDetail.0}}" readonly>
    </div>
    <div class="mb-3">
      <label for="kodeRoom" class="form-label">Kode Room</label>
      <input type="text" name="koderoom" class="form-control" id="kodeRoom" value="{{hotelRoomDetail.1}}" placeholder="{{hotelRoomDetail.1}}" readonly>
    </div>
    <div class="mb-3">
      <label for="jenisBed" class="form-label">Jenis Bed</label>
      <input type="text" name="jenisBed" class="form-control" id="jenisBed" placeholder="{{ hotelRoomDetail.2 }}" required>
    </div>
    <div class="mb-3">
        <label for="tipe" class="form-label">Tipe</label>
        <input type="text" name="tipe" class="form-control" id="tipe" placeholder="{{ hotelRoomDetail.3 }}" required>
    </div>
    <div class="mb-3">
        <label for="harga" class="form-label">Harga</label>
        <input type="text" name="harga" class="form-control" id="harga" placeholder="{{ hotelRoomDetail.4 }}" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}