faskes/urls.py
from django.urls import path

from . import views

app_name = 'faskes'

urlpatterns = [
    path('', views.read, name='read'),
    path('create/', views.create, name='create'),
    path('detail/<str:kode>', views.detail, name='detail'),
    path('update/<str:kode>', views.update, name='update'),
    path('updatePost/', views.updatePost, name='updatePost'),
    path('delete/<str:kode>', views.delete, name='delete'),
]

rs/urls.py
from django.urls import path

from . import views

app_name = 'rs'

urlpatterns = [
    path('', views.read, name='read'),
    path('create/', views.create, name='create'),
    path('update/<str:kode_faskes>', views.update, name='update'),
    path('updatePost/', views.updatePost, name='updatePost'),
]

siruco_e16/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("transaksi-makan/", include("transaksi_makan.urls")),
    path("paket-makan/", include("paket_makan.urls")),
    path("hotel/", include("hotel.urls")),
    path('', include('pengguna.urls')),
    path('pasien/', include('pasien.urls')),
    path('faskes/', include('faskes.urls')),
    path('reservasirs/', include('reservasirs.urls')),
    path('jadwalfaskes/', include('jadwalfaskes.urls')),
    path('rs/', include('rs.urls')),
    path('transaksirs/', include('transaksirs.urls')),
    path('dokter/', include('dokter.urls')),
    path('appointment/', include('appointment.urls')),
    path('roomnbed/', include('roomnbed.urls')),

]

faskes/models.py
from django.db import models

# Create your models here.

faskes/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.contrib import messages
from django.db.utils import IntegrityError, InternalError
from django.http import JsonResponse
import traceback
import json
from django.views.decorators.csrf import csrf_exempt

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def read(request):
    query = "SELECT * from faskes"
    with connection.cursor() as cursor:
        cursor.execute(query)
        data = dictfetchall(cursor)
    return render(request, 'faskes/read.html', {'data':data})

def detail(request, kode):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * from faskes WHERE kode=%s", [kode])
        res = dictfetchall(cursor)

    dataGet = {
        'kode' : res[0]['kode'],
        'tipe' : res[0]['tipe'],
        'nama' : res[0]['nama'],
        'statusmilik' : res[0]['statusmilik'],
        'jalan' : res[0]['jalan'],
        'kelurahan' : res[0]['kelurahan'],
        'kecamatan' : res[0]['kecamatan'],
        'kabkot' : res[0]['kabkot'],
        'prov' : res[0]['prov'],
    }
    return render(request, 'faskes/detail.html', {'data':dataGet})

@csrf_exempt
def create(request):
    if request.method == "POST":
        data = request.POST
        print(data)
        kode = str(data['kode'])
        tipe = str(data['tipe'])
        nama = str(data['nama'])
        statusmilik = str(data['statusmilik'])
        jalan = str(data['jalan'])
        kelurahan = str(data['kelurahan'])
        kecamatan = str(data['kecamatan'])
        kabkot = str(data['kabkot'])
        prov = str(data['prov'])

        
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO faskes VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);", 
            [kode, tipe, nama, statusmilik, jalan, kelurahan, kecamatan, kabkot, prov])

        return redirect("faskes:read")

    #tampilan form create
    username = request.session['username']
    with connection.cursor() as cursor:
        cursor.execute("SELECT kode FROM FASKES ORDER BY kode DESC LIMIT 1")
        res = cursor.fetchone()

    temp_kode = str(int(res[0]) + 1)
    if(len(temp_kode) == 1):
        new_kode = "00"+ temp_kode
    elif(len(temp_kode) == 2):
        new_kode = "0"+ temp_kode
    else: 
        new_kode = temp_kode
    return render(request, "faskes/create.html", 
    {'data' : new_kode,
    'message' : "Buat Faskes"
    })
    

def update(request, kode):
    #tampilan form update
    with connection.cursor() as cursor:
        cursor.execute("Select * from faskes where kode = %s", [kode])
        res = dictfetchall(cursor)

    dataGet = {
        'kode' : res[0]['kode'],
        'tipe' : res[0]['tipe'],
        'nama' : res[0]['nama'],
        'statusmilik' : res[0]['statusmilik'],
        'jalan' : res[0]['jalan'],
        'kelurahan' : res[0]['kelurahan'],
        'kecamatan' : res[0]['kecamatan'],
        'kabkot' : res[0]['kabkot'],
        'prov' : res[0]['prov'],
    }
    print(dataGet)
    return render(request, 'faskes/update.html', {'data': dataGet})

@csrf_exempt
def updatePost(request):
    if request.method == "POST":
        data = request.POST
        print(data)
        kode = str(data['kode'])
        tipe = str(data['tipe'])
        nama = str(data['nama'])
        statusmilik = str(data['statusmilik'])
        jalan = str(data['jalan'])
        kelurahan = str(data['kelurahan'])
        kecamatan = str(data['kecamatan'])
        kabkot = str(data['kabkot'])
        prov = str(data['prov'])
        
        with connection.cursor() as cursor:
            cursor.execute("""UPDATE FASKES set 
            tipe= %s,
            nama= %s,
            statusmilik= %s,
            jalan= %s,
            kelurahan= %s,
            kecamatan= %s,
            kabkot= %s,
            prov= %s where kode = %s""",
            [tipe, nama, statusmilik, jalan, kelurahan, kecamatan, kabkot, prov, kode])
            
        return redirect("faskes:read")


def delete(request, kode):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM FASKES WHERE kode=%s", [kode])
        return redirect("faskes:read")

faskes/templates/faskes/create.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}

<p>{{ message }}</p>

<form method="POST" action="{% url 'faskes:create' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="kode" class="form-label">Kode Faskes</label>
        <input type="text" name="kode" class="form-control" value='{{ data }}' id="kode" readonly>
    </div>
    <div class="mb-3">
        <label for="tipe" class="form-label">Tipe</label>
        <input type="text" name="tipe" class="form-control" id="tipe" required>
    </div>
    <div class="mb-3">
        <label for="nama" class="form-label">Nama Faskes</label>
        <input type="text" name="nama" class="form-control" id="nama" required>
    </div>
    <div class="mb-3">
        <label for="statusmilik" class="form-label">Status Kepemilikan</label>
        <input type="text" name="statusmilik" class="form-control" id="statusmilik" required>
    </div>
    <p>Alamat:</p>
    <div class="mb-3">
        <label for="jalan" class="form-label">Jalan</label>
        <input type="text" name="jalan" class="form-control" id="jalan" required>
    </div>
    <div class="mb-3">
        <label for="kelurahan" class="form-label">Kelurahan</label>
        <input type="text" name="kelurahan" class="form-control" id="kelurahan" required>
    </div>
    <div class="mb-3">
        <label for="kecamatan" class="form-label">Kecamatan</label>
        <input type="text" name="kecamatan" class="form-control" id="kecamatan" required>
    </div>
    <div class="mb-3">
        <label for="kabkot" class="form-label">Kabupaten/Kota</label>
        <input type="text" name="kabkot" class="form-control" id="kabkot" required>
    </div>
    <div class="mb-3">
        <label for="prov" class="form-label">Provinsi</label>
        <input type="text" name="prov" class="form-control" id="prov" required>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

faskes/templates/faskes/detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}

<h3>DATA FASILITAS KESEHATAN</h3>
<div>
  <p>Kode Faskes: {{ data.kode }}</p>
  <p>Tipe: {{ data.tipe }}</p>
  <p>Nama Faskes: {{ data.nama }}</p>
  <p>Status Kepemilikan: {{ data.statusmilik }}</p>
  <p>Alamat: </p>
  <p>Jalan: {{ data.jalan }}</p>
  <p>Kelurahan: {{ data.kelurahan }}</p>
  <p>Kecamatan: {{ data.kecamatan }}</p>
  <p>Kabupaten/Kota: {{ data.kabkot }}</p>
  <p>Provinsi: {{ data.prov }}</p>
</div>
<div class="pi-draggable btn-group" draggable="true">
  <a class="btn btn-primary" href="{% url 'faskes:read' %}"><b>Back</b></a>
</div>


{% endblock %}

faskes/templates/faskes/read.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Kode Faskes</th>
      <th scope="col">Tipe</th>
      <th scope="col">Nama Faskes</th>
      {% if request.session.peran == "admin satgas" %}
      <th scope="col">Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for row in data %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ row.kode }}</td>
      <td>{{ row.tipe }}</td>
      <td>{{ row.nama }}</td>
      <td>
        <div class="pi-draggable btn-group" draggable="true">
          <a class="btn btn-primary" href="{% url 'faskes:update' row.kode %}"><b>Update</b></a>
          <a class="btn btn-danger" href="{% url 'faskes:delete' row.kode %}"><b>Delete</b></a>
          <a class="btn btn-info" href="{% url 'faskes:detail' row.kode %}"><b>Detail</b></a>
        </div>
       </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

faskes/templates/faskes/update.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}

<form method="POST" action="{% url 'faskes:updatePost' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label for="kode" class="form-label">Kode Faskes</label>
        <input type="text" name="kode" class="form-control" value="{{ data.kode }}" id="kode" readonly>
    </div>
    <div class="mb-3">
        <label for="tipe" class="form-label">Tipe</label>
        <input type="text" name="tipe" class="form-control" value="{{ data.tipe }}" id="tipe" required>
    </div>
    <div class="mb-3">
        <label for="nama" class="form-label">Nama Faskes</label>
        <input type="text" name="nama" class="form-control" value="{{ data.nama }}" id="nama" required>
    </div>
    <div class="mb-3">
        <label for="statusmilik" class="form-label">Status Kepemilikan</label>
        <input type="text" name="statusmilik" class="form-control" value="{{ data.statusmilik }}" id="statusmilik" required>
    </div>
    
    <p>Alamat:</p>
    <div class="mb-3">
        <label for="jalan" class="form-label">Jalan</label>
        <input type="text" name="jalan" class="form-control" value="{{ data.jalan }}" id="jalan" required>
    </div>
    <div class="mb-3">
        <label for="kelurahan" class="form-label">Kelurahan</label>
        <input type="text" name="kelurahan" class="form-control" value="{{ data.kelurahan}}" id="kelurahan" required>
    </div>
    <div class="mb-3">
        <label for="kecamatan" class="form-label">Kecamatan</label>
        <input type="text" name="kecamatan" class="form-control" value="{{ data.kecamatan }}" id="kecamatan" required>
    </div>
    <div class="mb-3">
        <label for="kabkot" class="form-label">Kabupaten/Kota</label>
        <input type="text" name="kabkot" class="form-control" value="{{ data.kabkot }}" id="kabkot" required>
    </div>
    <div class="mb-3">
        <label for="prov" class="form-label">Provinsi</label>
        <input type="text" name="prov" class="form-control" value="{{ data.prov }}" id="prov" required>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>


{% endblock %}